version: '3.7'

services:
  backend:
    container_name: demo_graphql_backend
    restart: always
    build: .
    volumes:
      - ./src:/var/www/demo_graphql/src
    working_dir: /var/www/demo_graphql
    ports:
      - '3000:3000'
    links:
      - mysql
    depends_on:
      - mysql
  generation:
    container_name: demo_graphql_generation
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile.generation
    volumes:
      - ./src:/var/www/demo_graphql/src
    working_dir: /var/www/demo_graphql
  mysql: # Example Service
    container_name: demo_graphql_mysql
    restart: always
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=demo_graphql
      - MYSQL_PASSWORD=demo_graphql
      - MYSQL_DATABASE=demo_graphql
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql

volumes:
  data:
