version: "3.7"

services:
  backend:
    container_name: demo_graphql_backend
    restart: always
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend/src:/var/www/demo_graphql/src
    working_dir: /var/www/demo_graphql
    ports:
      - "3000:3000"
    links:
      - mysql
    depends_on:
      - mysql
  generation:
    container_name: demo_graphql_generation
    restart: always
    build:
      context: ./backend
      dockerfile: ./Dockerfile.generation
    volumes:
      - ./backend/src:/var/www/demo_graphql/src
    working_dir: /var/www/demo_graphql
  mysql:
    container_name: demo_graphql_mysql
    restart: always
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=demo_graphql
      - MYSQL_PASSWORD=demo_graphql
      - MYSQL_DATABASE=demo_graphql
    ports:
      - "3306:3306"
    volumes:
      - ./backend/data:/var/lib/mysql
  frontend:
    container_name: demo_graphql_frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend:/var/www/demo_graphql
    working_dir: /var/www/demo_graphql
    ports:
      - "4200:4200"
